# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Keypair < Formula
  desc ""
  homepage "https://github.com/keypairdev/keypair"
  version "0.0.9"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/keypairdev/releases/raw/main/keypair_0.0.9_darwin_arm64.tar.gz"
      sha256 "7a86c6f732329ef6c0d24367064891d0945c19173cb3adb68d550acccfa89010"

      def install
        bin.install "keypair"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/keypairdev/releases/raw/main/keypair_0.0.9_darwin_amd64.tar.gz"
      sha256 "d6c39406fa7b8a436c79a3efa3d4e536b044bb8524926c90a34b531642a2b371"

      def install
        bin.install "keypair"
      end
    end
  end

  service do
    run [opt_bin/"keypair", "server"]
    keep_alive true
    log_path "#{var}/log/keypair.log"
    error_log_path "#{var}/log/keypair.log"
  end
end
